#!/usr/bin/env python3
"""Extract the IQ* codebook tables from a llama.cpp checkout and emit them as a
self-contained C++ translation unit, so dsv4 can dequantise IQ1_M / IQ2_XXS / IQ3_XXS ...
without linking ggml (this tree stays additive: llama.cpp is only READ).

  python3 tools/extract_iq_tables.py [LLAMA_CPP_DIR] [OUT_CPP] [OUT_HPP]

Defaults: LLAMA_CPP_DIR=/home/user/workspaces/llama.cpp
          OUT_CPP=src/iq_tables.cpp  OUT_HPP=include/dsv4/iq_tables.hpp
"""
import os
import re
import sys

TABLES = [
    # (name, c type, used as)
    ("kmask_iq2xs",  "uint8_t"),
    ("ksigns_iq2xs", "uint8_t"),
    ("iq2xxs_grid",  "uint64_t"),
    ("iq2xs_grid",   "uint64_t"),
    ("iq2s_grid",    "uint64_t"),
    ("iq3xxs_grid",  "uint32_t"),
    ("iq3s_grid",    "uint32_t"),
    ("iq1s_grid",    "uint64_t"),
    ("kvalues_iq4nl", "int8_t"),
]

BEGIN = re.compile(r"GGML_TABLE_BEGIN\(\s*([A-Za-z0-9_]+)\s*,\s*([A-Za-z0-9_]+)\s*,\s*([A-Za-z0-9_]+|\d+)\s*\)")
CONST = re.compile(r"#define\s+(NGRID_IQ1S|QK_K)\s+(\d+)")


def find_common_h(root):
    for cand in ("ggml/src/ggml-common.h", "ggml-common.h", "ggml/src/ggml-common.h".lower()):
        p = os.path.join(root, cand)
        if os.path.isfile(p):
            return p
    raise SystemExit("cannot find ggml-common.h under %s" % root)


def parse(text):
    consts = {m.group(1): int(m.group(2)) for m in CONST.finditer(text)}
    out = {}
    pos = 0
    while True:
        m = BEGIN.search(text, pos)
        if not m:
            break
        pos = m.end()
        # skip the `#define GGML_TABLE_BEGIN(...)` macro definitions themselves
        bol = text.rfind("\n", 0, m.start()) + 1
        if text[bol:m.start()].strip().startswith("#define"):
            continue
        ctype, name, size = m.group(1), m.group(2), m.group(3)
        n = consts.get(size, None) if not size.isdigit() else int(size)
        end = text.index("GGML_TABLE_END()", m.end())
        body = text[m.end():end]
        vals = []
        for tok in body.replace("\n", " ").split(","):
            tok = tok.strip()
            if not tok:
                continue
            vals.append(int(tok, 0))
        if n is not None and len(vals) != n:
            raise SystemExit("%s: expected %d values, parsed %d" % (name, n, len(vals)))
        out[name] = (ctype, vals)
    return out


def emit(tables, out_cpp, out_hpp, src_path):
    hpp = [
        "// GENERATED by tools/extract_iq_tables.py - DO NOT EDIT.",
        "// Source: %s" % src_path,
        "// Codebook tables required to dequantise the IQ* ggml types.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace dsv4 {",
        "namespace iq {",
        "",
    ]
    for name, (ctype, vals) in tables.items():
        hpp.append("extern const %s %s[%d];" % (ctype, name, len(vals)))
    hpp += [
        "",
        "constexpr int kQkK = 256;          // QK_K",
        "constexpr int kNgridIq1s = %d;     // NGRID_IQ1S" % (len(tables["iq1s_grid"]) if "iq1s_grid" in tables else 2048),
        "constexpr float kIq1sDelta = 0.125f;",
        "",
        "}  // namespace iq",
        "}  // namespace dsv4",
        "",
    ]

    cpp = [
        "// GENERATED by tools/extract_iq_tables.py - DO NOT EDIT.",
        "// Source: %s" % src_path,
        "#include \"dsv4/iq_tables.hpp\"",
        "",
        "namespace dsv4 {",
        "namespace iq {",
        "",
    ]
    for name, (ctype, vals) in tables.items():
        cpp.append("const %s %s[%d] = {" % (ctype, name, len(vals)))
        line = []
        for i, v in enumerate(vals):
            if ctype == "int8_t":
                s = "%d" % v
            else:
                s = "0x%x" % (v & 0xFFFFFFFFFFFFFFFF)
            line.append(s)
            if len(line) == 8:
                cpp.append("    " + ", ".join(line) + ",")
                line = []
        if line:
            cpp.append("    " + ", ".join(line))
        cpp.append("};")
        cpp.append("")
    cpp += ["}  // namespace iq", "}  // namespace dsv4", ""]

    os.makedirs(os.path.dirname(out_cpp), exist_ok=True)
    os.makedirs(os.path.dirname(out_hpp), exist_ok=True)
    open(out_cpp, "w").write("\n".join(cpp) + "\n")
    open(out_hpp, "w").write("\n".join(hpp) + "\n")
    for name, (ctype, vals) in tables.items():
        print("  %-14s %-9s %6d entries" % (name, ctype, len(vals)))
    print("wrote %s (%d lines) and %s" % (out_cpp, len(cpp), out_hpp))


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "/home/user/workspaces/llama.cpp"
    out_cpp = sys.argv[2] if len(sys.argv) > 2 else "src/iq_tables.cpp"
    out_hpp = sys.argv[3] if len(sys.argv) > 3 else "include/dsv4/iq_tables.hpp"
    src = find_common_h(root)
    tables = parse(open(src, "r", errors="replace").read())
    missing = [n for n, _ in TABLES if n not in tables]
    if missing:
        raise SystemExit("tables not found in %s: %s" % (src, ", ".join(missing)))
    keep = {n: tables[n] for n, _ in TABLES}
    print("source: %s" % src)
    emit(keep, out_cpp, out_hpp, src)


if __name__ == "__main__":
    main()
