// dsv4/dequant.hpp - ggml quantisation types: row sizes, dequantisation and row dot products.
// The math is a faithful port of llama.cpp's ggml/src/ggml-quants.c (dequantise_row_*), so the
// CPU reference and the GPU kernels see exactly the same weights. IQ* codebooks live in
// src/iq_tables.cpp, generated by tools/extract_iq_tables.py (llama.cpp is only READ).
#pragma once

#include <cstddef>
#include <cstdint>

namespace dsv4 {

// REAL ggml type ids: they must match ggml.h and the GGUF files on disk.
enum GgmlType : uint32_t {
    T_F32 = 0,     T_F16 = 1,      T_Q4_0 = 2,   T_Q4_1 = 3,   T_Q5_0 = 6,   T_Q5_1 = 7,
    T_Q8_0 = 8,    T_Q2_K = 10,    T_Q3_K = 11,  T_Q4_K = 12,  T_Q5_K = 13,  T_Q6_K = 14,
    T_Q8_K = 15,   T_IQ2_XXS = 16, T_IQ2_XS = 17, T_IQ3_XXS = 18, T_IQ1_S = 19, T_IQ4_NL = 20,
    T_IQ3_S = 21,  T_IQ2_S = 22,   T_IQ4_XS = 23, T_I8 = 24,   T_I16 = 25,   T_I32 = 26,
    T_I64 = 27,    T_F64 = 28,     T_IQ1_M = 29,  T_BF16 = 30,  T_MXFP4 = 39
};

/// True when dequant_row() can decode this ggml type.
bool dequant_supported(uint32_t type);

/// Bytes of one row of `in` elements; 0 when the type is unknown or `in` is not a whole number of blocks.
size_t row_bytes(uint32_t type, int64_t in);

/// Number of elements per quantisation block (1 for the non-blocked types); 0 for unknown types.
int dequant_block_elems(uint32_t type);

/// Decode one row of `in` elements into float32 y[in]. Unsupported types leave y untouched.
void dequant_row(uint32_t type, const uint8_t* w, int64_t in, float* y);

/// dot(w_row, x) with the row decoded on the fly. Returns 0 for unsupported types.
float row_dot(uint32_t type, const uint8_t* w, const float* x, int64_t in);

}  // namespace dsv4
