/**
 * @file iq_tables.hpp
 * @brief IQ* quantization codebook lookup tables, generated from llama.cpp.
 *
 * These constant arrays are the dequantization codebooks for all IQ-type ggml quantizations:
 * IQ1_S, IQ2_XXS, IQ2_XS, IQ2_S, IQ3_XXS, IQ3_S, and the MXFP4 mantissa table (kvalues_iq4nl).
 *
 * Generated by [`tools/extract_iq_tables.py`](../../tools/extract_iq_tables.py) from llama.cpp's
 * `ggml/src/ggml-common.h`. The source is never modified — only read. Regenerate with:
 * @code
 *   python3 tools/extract_iq_tables.py ~/workspaces/llama.cpp src/iq_tables.cpp include/dsv4/iq_tables.hpp
 * @endcode
 *
 * @par Usage in dequantization
 *   The `at()` methods in [`dq_traits.hpp`](dq_traits.hpp) index into these tables using computed
 *   offsets from the quantized values. Under nvcc, the same code reads from `__constant__` memory
 *   (defined via macro substitution before including this header).
 */
#pragma once

#include <cstdint>

namespace dsv4 {
namespace iq {

/**
 * @var kmask_iq2xs[8]
 * @brief IQ2_XS sign mask table: 8 bytes, one per sub-element position.
 *
 * Each byte has bit N set if the N-th element in a group should be negated.
 */
extern const uint8_t kmask_iq2xs[8];

/**
 * @var ksigns_iq2xs[128]
 * @brief IQ2 XS sign lookup table: 128 entries for all IQ* types that share it.
 *
 * Indexed by a 7-bit field from the quantized data, returns a byte with sign bits for 8 elements.
 */
extern const uint8_t ksigns_iq2xs[128];

/**
 * @var iq2xxs_grid[256]
 * @brief IQ2_XXS codebook grid: 256 entries, each a 4-bit value (stored in 8 bits).
 *
 * Indexed by a 7-bit field from the quantized data plus an offset. Each entry is one of the
 * possible dequantized values for that sub-block position.
 */
extern const uint64_t iq2xxs_grid[256];

/**
 * @var iq2xs_grid[512]
 * @brief IQ2_XS codebook grid: 512 entries, each a 5-bit value (stored in 8 bits).
 *
 * Larger than IQ2_XXS because it stores per-group scales separately.
 */
extern const uint64_t iq2xs_grid[512];

/**
 * @var iq2s_grid[1024]
 * @brief IQ2_S codebook grid: 1024 entries, each a 6-bit value (stored in 8 bits).
 *
 * The largest of the IQ2 family grids, providing finer quantization at higher memory cost.
 */
extern const uint64_t iq2s_grid[1024];

/**
 * @var iq3xxs_grid[256]
 * @brief IQ3_XXS codebook grid: 256 entries, each a 4-bit value (stored in 8 bits).
 */
extern const uint32_t iq3xxs_grid[256];

/**
 * @var iq3s_grid[512]
 * @brief IQ3_S codebook grid: 512 entries, each a 5-bit value (stored in 8 bits).
 */
extern const uint32_t iq3s_grid[512];

/**
 * @var iq1s_grid[2048]
 * @brief IQ1_S codebook grid: 2048 entries, each a 7-bit signed value (stored in 8 bits as int8).
 *
 * The primary quantization for DeepSeek-V4-Flash. Smallest grid but coarsest per-value precision.
 */
extern const uint64_t iq1s_grid[2048];

/**
 * @var kvalues_iq4nl[16]
 * @brief IQ4_NL / IQ4_XS mantissa values: 16 entries (4-bit unsigned → signed).
 *
 * Values: {0, 1, 2, 3, 4, 6, 8, 12, -16, -1, -2, -3, -4, -6, -8, -12}.
 * Bit 7 = sign bit. Note the gap at 5 and 7 (non-uniform quantization).
 */
extern const int8_t kvalues_iq4nl[16];

/**
 * @def kQkK
 * @brief Standard K-quant block size: 256 elements per block.
 *
 * Used by Q4_K, Q5_K, Q6_K, Q8_K, and all IQ* types (except non-blocked F32/F16/etc.).
 */
constexpr int kQkK = 256;

/**
 * @def kNgridIq1s
 * @brief Number of grid entries per sub-block in IQ1_S: 2.
 *
 * Each 32-element sub-block uses one of two possible grids (indexed by the high bits).
 */
constexpr int kNgridIq1s = 2;

/**
 * @def kIq1sDelta
 * @brief IQ1_S per-sub-block delta offset: ±0.125.
 *
 * Each sub-block of IQ1_S has a 3-bit scale multiplier and an additional ±0.125 fine adjustment
 * encoded in the high bits of the quantized data.
 */
constexpr float kIq1sDelta = 0.125f;

}  // namespace iq
}  // namespace dsv4
