// GENERATED by tools/extract_iq_tables.py - DO NOT EDIT.
// Source: /home/user/workspaces/llama.cpp/ggml/src/ggml-common.h
// Codebook tables required to dequantise the IQ* ggml types.
#pragma once
#include <cstdint>

namespace dsv4 {
namespace iq {

extern const uint8_t kmask_iq2xs[8];
extern const uint8_t ksigns_iq2xs[128];
extern const uint64_t iq2xxs_grid[256];
extern const uint64_t iq2xs_grid[512];
extern const uint64_t iq2s_grid[1024];
extern const uint32_t iq3xxs_grid[256];
extern const uint32_t iq3s_grid[512];
extern const uint64_t iq1s_grid[2048];
extern const int8_t kvalues_iq4nl[16];

constexpr int kQkK = 256;          // QK_K
constexpr int kNgridIq1s = 2;     // NGRID_IQ1S
constexpr float kIq1sDelta = 0.125f;

}  // namespace iq
}  // namespace dsv4

