# cmake/mmq_types.cmake - the single source of truth for the GGML types the MMQ prompt path covers.
#
# One list drives BOTH sides of the MMQ wrapper:
#   * the mmq-instance-<type>.cu files that get compiled into strata_mmq, and
#   * the supported()/dispatch table of src/prefill/moe_mmq.cu, generated from the same list as an X-macro.
#
# They cannot drift apart.  A type that is not compiled is not advertised, and a type that is advertised is
# instantiated - so mul_mat_q_case<...> can never reference a template that was never instantiated.  Drift here
# broke the build in both directions before: an advertised type with no instance is an undefined symbol, and an
# instance that is not advertised silently switches the whole prompt path off, which costs 100x on prefill
# (docs/UNSLOTH_Q4.md).
#
# strata_gen_mmq_types(<output-file> <types>)
#   Writes an X-macro header listing every type in <types>, given as the GGML template-instances suffixes
#   (q4_0, iq2_xs, q6_k, ...).  The header defines STRATA_MMQ_TYPES(X), which applies X to the uppercased name
#   of each type without the GGML_TYPE_ prefix, so X(Q4_K) expands to whatever GGML_TYPE_Q4_K is needed.
function(strata_gen_mmq_types out_file types)
    set(_rows "")
    foreach(_t IN LISTS types)
        if(NOT _t MATCHES "^[a-z0-9_]+$")
            message(FATAL_ERROR "strata_gen_mmq_types: bad MMQ type name '${_t}'")
        endif()
        string(TOUPPER "${_t}" _T)
        list(APPEND _rows "    X(${_T})")
    endforeach()
    if(NOT _rows)
        message(FATAL_ERROR "strata_gen_mmq_types: the MMQ type list is empty")
    endif()
    # " \\\n" is a line continuation plus a newline: the macro body must read as one continued line.
    list(JOIN _rows " \\\n" _body)
    set(_content
"// GENERATED by cmake/mmq_types.cmake from the CMake MMQ type list - DO NOT EDIT.
//
// The list of GGML types this build compiles MMQ instances for.  src/prefill/moe_mmq.cu derives both
// supported() and the mul_mat_q_case dispatch from it, so what the engine advertises and what the linker has
// are the same set by construction.
#pragma once

#define STRATA_MMQ_TYPES(X) \\
${_body}
")
    # file(GENERATE) rewrites only when the content changes, so an unchanged type list does not rebuild strata_mmq.
    file(GENERATE OUTPUT "${out_file}" CONTENT "${_content}")
    set(STRATA_MMQ_TYPES_FILE "${out_file}" PARENT_SCOPE)
endfunction()
